language: go
sudo: required
services:
- docker
go:
- 1.6
before_install:
- openssl aes-256-cbc -K $encrypted_1aa0da41d635_key -iv $encrypted_1aa0da41d635_iv
  -in payment_deploy_rsa.enc -out payment_deploy_rsa -d
- go get github.com/gorilla/mux
- go get github.com/go-kit/kit/endpoint
- go get github.com/go-kit/kit/transport/http
install: true
env:
- GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=payment;
script:
- set -e
- "./scripts/build.sh;"
- "./test/test.sh unit.py"
- "./test/test.sh container.py --tag $COMMIT"
after_success:
- set -e;
- if [ -z "$DOCKER_PASS" ] ; then echo "This is a build triggered by an external PR.
  Skipping docker push."; exit 0; fi;
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
- "./scripts/push.sh"
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
addons:
  ssh_known_hosts: "$BASTION"
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION ./deploy.sh ${REPO}
    $COMMIT
  on:
    branch: master
notifications:
  slack:
    secure: cRuwjAXZg1i/1qqQeeIe/Q0WmNE/WKOBvG+IWz/EDE/8sJBx67TugGIovCqW9J4VZX5hpzhGbnWV2535/+aHihbaquQ+2kO81EJaILD7MUoi2mxoIHH0KoMe/nYnI/Grdjv6+JbqybLfK3nQfq7sBQDbG8Qi4b7IcO2Bxg5Q9vUsRzJ1/NYNdDk/coEPlEDs+R0WqxmEFmVGDlZvbzNyMEzokkZIW+xEu8T9Qjr51Jn84zfQ1J46+y/ZNLKI+5oScX6JI4a2cYEopfwX2lQREl1YuL+NyuQw0jJy/mxtkai501XTiht7XOYbI+kmwj9+NIGQWGHlXSD7Q4Nrd/0MdMaAlUXxb+xlZ4uY1IpZnMfWT4nIe1SIr3hnwtIOrVcEwrElWvhm3dk3Lmrz46v0JUXkYh4DxEnMucYon0Q+4EoNRHFQWMSeKQNXrZocxu/DMTgiISUsE3lmqbL7SKMV27wDgyGaiWqgmMcmbR6d/gOilbbLoK9L2wtRaqPMpk4lAoIyzxt+EIs/iT73UHV3lz3/7a3QuIwC3T4BqwykT+8ioUW9QBlB8OeW2QQxIerxAGD+/Rwlb3+mAvnqqPfkXMoyEu+0MPuQg4hA/+ZXba9wivZMk57AM14hJO9EPYhcsf6V8FJHn8WDdCKGW95Kp8el5eJ22V2mIUQ5WLygReM=
